### ISSUE TITLE
Is the deconvolution result highly dependent the cell types annotation of the scRNAseq reference data?

### ISSUE THREAD

**Issue by ShaowenJ** [theislab/AutoGeneS#16]
Hi, thanks for developing this tool.

I was wondering about my title's question.
Here is what I did to come up with this question.

I am currently using a scRNAseq data of Breast cancer cohort from a published paper to deconvolute the TCGA-BRCA bulk RNAseq.
After generating the deconvolution proportion matrices from using a general cell annotation and a detailed cell annotation (i.e. more immune cell subgroups), I compared their cancer cell proportions (annotation of cancer cells are the same) with TCGA purity. 
It turns out that the proportion matrices are a little different, cancer cell proportion from the detailed annotation is relatively lower than the other.  And the Pearson correlation with purity is totally different.

And based on the methods of generating the signature matrix, I guess it is important to make a relative correct annotation of your scRNAseq data before using it to deconvolute? Am I right?

Thanks for any response.

**Comment by lila167** [comment]
Hi,

Thanks for using our tool! 

The answer is yes, AutoGeneS works with mean expression of cell types, so it needs a relatively good annotation of cells. Of course, when you have a lot of cells per cell type, few misannotations can be masked. 
When you have multiple conditions (healthy vs disease), sometimes you need different reference matrix for each. 
Also, with any deconvolution method, you should compare relative changes of proportions across samples rather than absolute cell proportions. 

Best

**Comment by GV20jsw** [comment]
Hi @lila167 ,

Thanks very much for the comment.

I have another question if my single-cell reference has multiple patients or conditions like breast cancer has different subtypes (ER+, HER2+, Basal), should I separate them individually for deconvolution?

**Comment by ShaowenJ** [comment]
Hi @lila167 ,

Thanks very much for the comment.

I have another question if my single-cell reference has multiple patients or conditions like breast cancer has different subtypes (ER+, HER2+, Basal), should I separate them individually for deconvolution?

**Comment by lila167** [comment]
This depends on the difference between the patients data. For an example, please refer to Fig. 5 in our paper: https://www.sciencedirect.com/science/article/pii/S2405471221001927
