### ISSUE TITLE
Healthy Vs Pateint signature

### ISSUE THREAD

**Issue by mms100** [theislab/AutoGeneS#19]
Hi,

Thanks for the valuable tool.

I have a single cell RNA-seq dataset that includes:

3 samples healthy == 3 batches
3 samples patients == 3 batches

Can I build up a signature matrix by comparing the 3 healthy Vs 3 patients?

my first issue:
The main issue here is that I have two levels of batch effect:
1- Within the 3 samples with each condition 
2- Within the two condition 

my second issue:
I have bulk RNA-seq data that have 4 samples, 2 healthy and 2 patients, and I want to confirm if, for instance, the 2 healthy samples are more similar to the healthy samples that are coming from the 3 SC RNA-seq samples or not.

So this is another issue of correcting the batch while comparing the SC-RNA-seq dataset to the Bulk RNA-seq

N.B. the bulk data don't have any batch.

Many thanks in advance,
Mohamed

**Comment by lila167** [comment]
Hi,

Thanks for using our tool. 
The last example in our paper is similar to your problem because we also had healthy and disease samples. The right way of deconvolution depends on your data. Do you expect some cell types to vary between healthy and disease? If yes, I recommend to annotate them separately. For example cell_type_A_healthy and cell-type_A_disease. Then AutoGeneS should be able to find the differentiating genes across those conditions. Regarding the batches across healthy (or disease) samples, often AutoGeneS can find the genes that are not batch affected. You can check that by visualizing your data using important genes (often 300-400 genes). The batches often overlap nicely :)

Best,
Hana
