### ISSUE TITLE
Couldn't find documentation of `ag.run`

### ISSUE THREAD

**Issue by vitkl** [theislab/AutoGeneS#2]
Very excited to test your package! Could you please point me to the description of `ag.run` arguments?

<img width="919" alt="Screen Shot 2020-03-20 at 13 37 30" src="https://user-images.githubusercontent.com/22567383/77168645-0e9a4100-6ab0-11ea-8c97-eac39bd39a25.png">

**Comment by maxims94** [comment]
We will very soon publish a new version of AutoGenes, which will also include extensive documentation. I will update this thread once it is ready.

**Comment by lila167** [comment]
@vitkl Happy that you want to try our tool. As Maxim said, we are working on the documentation. Sorry for that. 
For the moment, you can specify the total number of marker genes using "nfeatures". I recommend something between 300-500. "ngen" specifies the number of optimization runs. You can set it to 5K. Objectives are also by default distance and correlation. You can also define your own objectives that will be explained in our documentation. "weights" also show wether your objectives are to be maximized or minimized.

**Comment by vitkl** [comment]
Thanks for explaining the details for now!

This probably deserves it's own issue but I get rather weird correlation by distance plots compared to your examples.
![image](https://user-images.githubusercontent.com/22567383/77430690-7663cb00-6dd3-11ea-9c2d-d19bd1de2a54.png)

I am looking at 50 cluster centroids / averages for 5000 HVGs and `nfeatures = 500`.

**Comment by lila167** [comment]
50 clusters sound a lot to me. I'm happy that you are trying in on that many cell types, but I fear the correlation is very high between the clusters as you see it also on the plot. I would suggest you to lower the resolution of your clusters. Also, 500 genes should not be enough for differentiating 50 clusters.

**Comment by vitkl** [comment]
50 clusters makes sense in the context of mouse brain biology (multiple regions), it is even not granular enough. Actually I tried using `nfeatures = 1000` and `nfeatures = 2000` but got exactly the same plot. So does this plot mean that any gene selection explored by your model that increases distance between cell types also increases correlation between them?

**Comment by lila167** [comment]
What do you mean by exactly the same plot? do you mean a similar trend?
Correlation and distance can be contrary. Meaning that minimizing correlation, doesn't maximize the distance necessarily and this is exactly why we need a multi-objective optimization. If you see an almost linear trend, it can be that the optimization has not converged yet. If so, I recommend to increase ngen. What is ngen in this example? It can also be that this is just the nature of your data.

**Comment by lila167** [comment]
Also, try to plot the correlation matrix after selecting a solution from your pareto front. It can show you how correlated your cell types are. To me, the correlation is extremely high in your data.

**Comment by maxims94** [comment]
> So does this plot mean that any gene selection explored by your model that increases distance between cell types also increases correlation between them?

Yes, because we only consider pareto front solutions. Think about it this way: If you have two solutions with the same correlation, but one has higher distance, you can discard the one with lower distance. Our tool only offers solutions that are not strictly dominated by some other solution. So, if you pick a solution with better (higher) distance, you have to accept a worse (higher) correlation.

In the next version, you will be able to tweak more parameters of the evolutionary algorithm (that are hardcoded right now). Maybe this will lead to a different pareto front. I agree that the linear relationship is strange.

**Comment by vitkl** [comment]
I mean I saw a similar trend of a strong correlation between the distance and correlation.
I used ngen=50k as in your examples and it took ~ 50 minutes on a 40-threaded machine (but I do not know how many threads were used).
If could be the globally high correlations driven by the difference in expression level of genes, e.g. Malat1 is always highly expressed and very cell-type specific genes are almost never expressed (except the correct cell type). This is what correlations look like before HVG selection and AutoGeneS but it is similar after the HVG too. 
![image](https://user-images.githubusercontent.com/22567383/77484065-81dde300-6e21-11ea-8e00-1eb0e5670955.png)

**Comment by lila167** [comment]
There are some points to consider when working with an optimizer: 1) when the size of the problem increases, calculating the objective functions can get longer. In your case, you have 50 cell types that is almost 10 times more than the example in this repo. For every solution that the optimizer explores, it should measure corr and dist for 50 cell types. This is why you see higher execution time. 2) All the heuristic-based optimizations search through only a small part of the search space because it's often impossible to search the whole space. So, if you increase the size of your problem, you increase the search space as well which decreases the chance to find optimum solutions unless you change the parameters like ngen, n_features,.. or run the code in parallel with several starting points and aggregate the results. 3) If a feature that you expect doesn't exist, it can mean that the optimizer found solutions with better objective values without that gene or the optimizer didn't explore that because it was in the unexplored space. 4) With AutoGeneS, you should not necessarily expect to get  well-defined markers because it's goal (specified as objectives) is not to find the genes that are highly expressed in one cell type. If you want to have that, you should customize your objective function.
