### ISSUE TITLE
How to interpret the score

### ISSUE THREAD

**Issue by grst** [theislab/AutoGeneS#3]
Hi, 

I was wondering about the properties of AutoGeneS' cell-type score. I couldn't find any information in the manuscript if the score
 * is relative to the total immune cell fraction (like CIBERSORT), which only allows comparisons between cell-types
 * is an absolute cell-type fraction, which allows comparisons between both samples and cell-types (like [EPIC](https://github.com/GfellerLab/EPIC))
 * is in arbitrary units, which allows comparisons between samples, but not cell-types. 

For more background-information, see also the introduction of [our benchmark paper](https://academic.oup.com/bioinformatics/article/35/14/i436/5529146) of "1st-gen" deconvolution methods. 

Best regards, 
Gregor

**Comment by lila167** [comment]
Hi Gregor,

Thanks for your comment. AutoGenes is a feature selection method. The regression can be orthogonal to that. In the way we use it (svr or nnls), we don't consider cell sizes. If one corrects the reference profile for the cell sizes, then the deconvolution results can be used as the absolute cell type proportions. Otherwise, the comparison between samples makes more sense. By that, I mean whether the proportion of one cell type is increasing or decreasing across samples.  
Another issue is the compositional nature of the regression. That means the proportions are summed to 1. So, if you capture high proportion in one cell type, the other cell types should get less proportions to be summed to 1. To make it relative, one can divide the proportions to the proportion of one specific cell type (similar to Cibersort). 

I hope these help.
Hana

**Comment by grst** [comment]
Thanks a lot, that helps!
