### ISSUE TITLE
Do I have to start with highly variable genes?

### ISSUE THREAD

**Issue by brianpenghe** [theislab/AutoGeneS#6]
Based on the example, it seems that AutoGeneS selects genes among highly variable genes.
But can I select genes from the whole transcriptome?

**Comment by lila167** [comment]
Hi, yes you can do that as well. set use_highly_variable to False. The idea of using highly variable genes is to shrink the search space.

**Comment by brianpenghe** [comment]
But I thought in your example you updated adata to make it contain only 4000 highly variable genes. So if I want to use all genes, I should keep all the genes AND set use_highly_variable to True right?

**Comment by lila167** [comment]
If you are feeding autogenes with Anndata, setting ```use_highly_variable=True``` looks for the highly variable genes in the ```adata.var['hihgly_variable']``` and filter those. So, if your adata contains all genes and you set ```use_highly_variable=False```, autogenes uses all genes. As I said, I don't recommend to go with all genes because there are a lot of noisy and not informative genes besides the fact that this increases the search space. You can always increase the number of highly variable genes though. Finally, if you feed autogenes with pandas dataframe or numpy, all genes will be used by autogenes.
